### ISSUE TITLE
Add support for RIPEMD160 hashing

### ISSUE THREAD

**Issue by eMaringolo** [PierceNg/OpenSSL-Pharo#2]
Implement the FFI calls and required classes to support RIPEMD160 hashing

`unsigned char *` `RIPEMD160(const unsigned char *d, unsigned long n, unsigned char *md)`
`int` `RIPEMD160_Init(RIPEMD160_CTX *c)`
`int` `RIPEMD160_Update(RIPEMD_CTX *c, const void *data, unsigned long len)`
`int` `RIPEMD160_Final(unsigned char *md, RIPEMD160_CTX *c)`

**Comment by PierceNg** [comment]
Added using the EVP interface. Check out the unit tests.

**Comment by eMaringolo** [comment]
I added it to remind me adding it later, but you were faster. :)

Thank you @PierceNg !

**Comment by PierceNg** [comment]
Closed because done.
